name: Angular Project CI

on:
  push:
    branches:
      - main
      - qa
      - deveploy
      - feature-ci-cd

jobs:
  docker-build:
    uses: Poojamaney10/devops-github-actions/.github/workflows/angular-ci.yml@main

    with:
      image-name: angular-project

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
